name: CI - Calculadora FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          pytest --junitxml=report.xml

      - name: Compactar relatório de testes
        run: zip report.zip report.xml

      - name: Criar diretório de artefatos
        run: mkdir -p artifacts && mv report.zip artifacts/

      - name: Upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-testes
          path: artifacts/report.zip
