name: CI - Calculadora FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes e gerar relatório
        run: pytest --junitxml=report.xml

      - name: Criar Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Relatório CI ${{ github.run_number }}"
          body: "Relatório de testes gerado automaticamente."
          files: report.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
